output {
  if [event][module] == "Zeek" and [pipeline] == "dns" {
    tcp {
      id => "soc_lab_elk_zeek_dns"
      host => "ELK_HOST_ONLY_IP"
      port => 5514
      codec => json_lines
    }
  }
}

