input {
  tcp {
    id => "json_tcp_5514"
    port => 5514
    codec => json_lines
    tags => ["soc_lab", "json_tcp"]
  }

  udp {
    id => "json_udp_5514"
    port => 5514
    codec => json
    tags => ["soc_lab", "json_udp"]
  }

  syslog {
    id => "syslog_5515"
    port => 5515
    tags => ["soc_lab", "syslog"]
  }
}

filter {
  if ![event][dataset] {
    mutate {
      add_field => { "[event][dataset]" => "soc_lab.generic" }
    }
  }

  if "SOC_LAB_TEST" in [message] {
    mutate {
      add_tag => ["validation_event"]
      add_field => {
        "[rule][name]" => "SOC lab validation event"
        "[event][kind]" => "alert"
        "[event][category]" => "configuration"
        "[event][type]" => "info"
      }
    }
  }

  mutate {
    add_field => {
      "[observer][name]" => "elk-lite"
      "[observer][product]" => "Logstash"
      "[lab][name]" => "private-soc-lab"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "soc-lab-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}

